easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'Static/index.html.twig'

app_contacto:
    path: /contacto/
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'Static/contacto.html.twig'

app_credits:
    path: /creditos/
    defaults: 
        _controller: FrameworkBundle:Template:template 
        template:    'Static/credits.html.twig'
